#pragma once
#include <array>
#include <algorithm>
#include <cmath>
#include <cstddef>
// Native per-slot catalog, derived from the supplied Lua parameter definitions.
// Stable keys are persistent IDs; ordering is only an editor concern.
namespace lsampler {
enum class Kind { continuous, integer, enumeration, note, action };
struct Descriptor { const char* key; const char* name; const char* category; Kind kind;
    double initial, minimum, maximum, step, largeStep; const char* unit; int decimals; const char* labels; };
enum class P {
    input_gain,
    polyphony,
    slot_polyphony,
    poly_drift,
    portamento,
    legato,
    sustain_pedal,
    same_note_replace,
    pitch_bend_range,
    mode,
    output_route,
    ram_stereo_width,
    ram_swap_lr,
    ram_downsample,
    pan,
    low,
    high,
    root,
    octave,
    voice_pitch,
    vel_volume_depth,
    velocity_low,
    velocity_high,
    choke_trigger,
    choke_target,
    choke_mode,
    sample_start,
    sample_end,
    sample_play_start,
    start_threshold,
    end_threshold,
    end_preview_length,
    global_one_shot,
    start_end_fade,
    stereo_delay_left,
    stereo_delay_right,
    stretch_amount,
    stretch_frequency,
    normalize_on,
    normalize_target,
    transient_shape,
    transient_speed,
    transient_mix,
    ram_fade_in,
    ram_fade_out,
    ram_reverse,
    dc_remove,
    machine_character,
    character_depth,
    character_input_drive,
    character_converter,
    character_playback_life,
    character_repeat_life,
    character_air_body,
    character_output_glue,
    attack,
    decay,
    sustain,
    release,
    retrigger_smooth,
    pitch_env,
    pan_env,
    vel_attack_depth,
    lp_on,
    lp_cutoff,
    lp_resonance,
    lp_env_amount,
    lp_env_attack,
    lp_env_decay,
    lp_env_sustain,
    lp_env_release,
    lp_vel_amount,
    lp_key_follow,
    hp_on,
    hp_cutoff,
    hp_resonance,
    hp_env_amount,
    hp_env_attack,
    hp_env_decay,
    hp_env_sustain,
    hp_env_release,
    hp_vel_amount,
    lfo1_rate,
    lfo1_mode,
    lfo1_bpm_sync,
    lfo1_one_shot,
    lfo1_wave,
    lfo1_delay,
    lfo1_smoothing,
    lfo1_volume_depth,
    lfo1_pan_depth,
    lfo1_lp_depth,
    lfo1_hp_depth,
    lfo1_pitch_depth,
    lfo1_sample_depth,
    lfo2_rate,
    lfo2_mode,
    lfo2_bpm_sync,
    lfo2_one_shot,
    lfo2_wave,
    lfo2_delay,
    lfo2_smoothing,
    lfo2_volume_depth,
    lfo2_pan_depth,
    lfo2_lp_depth,
    lfo2_hp_depth,
    lfo2_pitch_depth,
    lfo2_mod_pitch_depth,
    lfo2_sample_depth,
    global_release_loops,
    loop_crossfade,
    drive_type,
    drive_amount,
    drive_position,
    comp_on,
    comp_threshold,
    comp_ratio,
    comp_attack,
    comp_release,
    comp_makeup,
    comp_mix,
    comp_delta,
    dynamics_order,
    gate_on,
    gate_threshold,
    gate_attack,
    gate_release,
    gate_hold,
    gate_depth,
    gate_mix,
    gate_delta,
    ring_mode,
    ring_wave,
    ring_amount,
    ring_freq,
    degrade_amount,
    degrade_bits,
    degrade_hold,
    degrade_jitter,
    fm_amount,
    fm_ratio,
    fm_wave,
    fm_feedback,
    count
};
enum class L { start, end, repeats, fade_in, fade_out, pitch_down, lp_down, hp_down, one_shot, count };
inline constexpr int parameterCount = 143, loopParameterCount = 9, loopCount = 10;
inline constexpr std::array<Descriptor, parameterCount> parameters {{
{"input_gain", "Level", "Slot", Kind::continuous, 0.0, -120.0, 24.0, 0.1, 1.0, "dB", 1, ""},
{"polyphony", "Voice Mode", "Slot", Kind::enumeration, 1.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Mono|Poly"},
{"slot_polyphony", "Slot Polyphony", "Slot", Kind::enumeration, 0.0, 0.0, 24.0, 1.0, 4.0, "", 0, "Auto|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24"},
{"poly_drift", "Poly Drift", "Slot", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"portamento", "Portamento", "Slot", Kind::integer, 0.0, 0.0, 1000.0, 1.0, 25.0, "ms", 0, ""},
{"legato", "Legato", "Slot", Kind::enumeration, 1.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"sustain_pedal", "Sustain Pedal", "Slot", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"same_note_replace", "Same Note Replace", "Slot", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"pitch_bend_range", "Pitch Bend Range", "Slot", Kind::continuous, 2.0, 0.0, 48.0, 0.1, 1.0, "semitones", 1, ""},
{"mode", "Audio", "Slot", Kind::enumeration, 1.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Mono|Stereo"},
{"output_route", "Slot Output", "Slot", Kind::enumeration, 0.0, 0.0, 24.0, 1.0, 1.0, "", 0, "Main 1/2|Out 3/4|Out 5/6|Out 7/8|Out 9/10|Out 11/12|Out 13/14|Out 15/16|Out 17/18|Out 19/20|Out 21/22|Out 23/24|Out 25/26|Out 27/28|Out 29/30|Out 31/32|Out 33/34|Out 35/36|Out 37/38|Out 39/40|Out 41/42|Out 43/44|Out 45/46|Out 47/48|Out 49/50"},
{"ram_stereo_width", "Audio Width", "Slot", Kind::continuous, 100.0, 0.0, 200.0, 0.1, 5.0, "%", 1, ""},
{"ram_swap_lr", "Audio Swap", "Slot", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Left Right|Right Left"},
{"ram_downsample", "RAM Downsample", "Slot", Kind::enumeration, 0.0, 0.0, 10.0, 1.0, 1.0, "", 0, "Off|32 kHz 16 bit|22 kHz 12 bit|22 kHz 8 bit|12 kHz 8 bit|12 kHz 4 bit|11 kHz 12 bit|11 kHz 8 bit|8 kHz 12 bit|8 kHz 8 bit|8 kHz 4 bit"},
{"pan", "Pan", "Slot", Kind::continuous, 0.0, -100.0, 100.0, 0.1, 5.0, "%", 1, ""},
{"low", "Low Key", "Mapping", Kind::note, 0.0, 0.0, 127.0, 1.0, 40.0, "", 0, ""},
{"high", "High Key", "Mapping", Kind::note, 127.0, 0.0, 127.0, 1.0, 40.0, "", 0, ""},
{"root", "Original Pitch", "Mapping", Kind::note, 60, 0.0, 127.0, 1.0, 40.0, "", 0, ""},
{"octave", "Octave", "Mapping", Kind::integer, 0.0, -4.0, 4.0, 1.0, 1.0, "", 0, ""},
{"voice_pitch", "Fine Pitch", "Mapping", Kind::continuous, 0.0, -9.6, 9.6, 0.001, 0.1, "semitones", 3, ""},
{"vel_volume_depth", "Velocity Volume Depth", "Mapping", Kind::continuous, 1.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"velocity_low", "Velocity Low", "Mapping", Kind::integer, 0.0, 0.0, 127.0, 1.0, 10.0, "", 0, ""},
{"velocity_high", "Velocity High", "Mapping", Kind::integer, 127.0, 0.0, 127.0, 1.0, 10.0, "", 0, ""},
{"choke_trigger", "Choke Trigger Note", "Mapping", Kind::note, -1.0, -1.0, 127.0, 1.0, 12.0, "", 0, ""},
{"choke_target", "Choke Target Note", "Mapping", Kind::note, -1.0, -1.0, 127.0, 1.0, 12.0, "", 0, ""},
{"choke_mode", "Choke Mode", "Mapping", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Kill|Release"},
{"sample_start", "Sample Start", "Sample Window", Kind::continuous, 0.0, 0.0, 100.0, 0.01, 0.25, "%", 3, ""},
{"sample_end", "Sample End", "Sample Window", Kind::continuous, 100.0, 0.0, 100.0, 0.01, 0.25, "%", 3, ""},
{"sample_play_start", "Sample Play Start", "Sample Window", Kind::continuous, 0.0, 0.0, 100.0, 0.01, 0.25, "%", 3, ""},
{"start_threshold", "Start Threshold", "Sample Window", Kind::continuous, -60.0, -120.0, 0.0, 0.1, 1.0, "dB", 1, ""},
{"end_threshold", "End Threshold", "Sample Window", Kind::continuous, -120.0, -120.0, 0.0, 0.1, 1.0, "dB", 1, ""},
{"end_preview_length", "End Preview Length", "Sample Window", Kind::enumeration, 0.0, 0.0, 12.0, 1.0, 1.0, "", 0, "Auto|50 ms|100 ms|200 ms|300 ms|500 ms|750 ms|1000 ms|1500 ms|2000 ms|3000 ms|4000 ms|5000 ms"},
{"global_one_shot", "Main Playback Mode", "Sample Window", Kind::enumeration, 1, 0.0, 2.0, 1.0, 1.0, "", 0, "Main Loop|One Shot|On Release"},
{"start_end_fade", "Start End Fade", "Sample Window", Kind::continuous, 0.0, 0.0, 100.0, 0.01, 0.1, "ms", 2, ""},
{"stereo_delay_left", "Stereo Delay Left", "Sample Window", Kind::continuous, 0.0, 0.0, 50.0, 0.01, 0.1, "ms", 2, ""},
{"stereo_delay_right", "Stereo Delay Right", "Sample Window", Kind::continuous, 0.0, 0.0, 50.0, 0.01, 0.1, "ms", 2, ""},
{"stretch_amount", "Stretch Amount", "Sample Window", Kind::continuous, 0.0, -64.0, 64.0, 0.01, 0.1, "", 3, ""},
{"stretch_frequency", "Stretch Frequency", "Sample Window", Kind::integer, 220.0, 10.0, 20000.0, 1.0, 1000.0, "Hz", 0, ""},
{"normalize_on", "Normalize", "Audio Sculpt", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"normalize_target", "Normalize Target", "Audio Sculpt", Kind::continuous, -6.0, -24.0, 0.0, 0.1, 1.0, "dB", 1, ""},
{"transient_shape", "Transient Shape", "Audio Sculpt", Kind::continuous, 0.0, -100.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"transient_speed", "Transient Speed", "Audio Sculpt", Kind::continuous, 25.0, 1.0, 500.0, 1.0, 10.0, "ms", 0, ""},
{"transient_mix", "Transient Mix", "Audio Sculpt", Kind::continuous, 100.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"ram_fade_in", "Fade In", "Audio Sculpt", Kind::continuous, 0.0, 0.0, 50.0, 0.01, 1.0, "ms", 2, ""},
{"ram_fade_out", "Fade Out", "Audio Sculpt", Kind::continuous, 0.0, 0.0, 50.0, 0.01, 1.0, "ms", 2, ""},
{"ram_reverse", "Reverse", "Audio Sculpt", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"dc_remove", "DC Remove", "Audio Sculpt", Kind::enumeration, 0, 0, 1, 1, 1, "", 0, "Off|On"},
{"machine_character", "Machine Character", "Machine", Kind::enumeration, 0.0, 0.0, 7.0, 1.0, 1.0, "", 0, "Off|Clean|L900|LEmax|L3200|LItalian|LBroken|LFuture"},
{"character_depth", "Character Depth", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_input_drive", "Input Drive", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_converter", "Converter Color", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_playback_life", "Playback Life", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_repeat_life", "Repeat Life", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_air_body", "Air Body", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"character_output_glue", "Output Glue", "Machine", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 100.0, "", 0, ""},
{"attack", "Env Attack", "Envelope", Kind::continuous, 0, 0.0, 20.0, 0.001, 0.01, "s", 3, ""},
{"decay", "Env Decay", "Envelope", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "s", 3, ""},
{"sustain", "Env Sustain", "Envelope", Kind::continuous, 1.0, 0.0, 1.0, 0.01, 0.1, "", 2, ""},
{"release", "Env Release", "Envelope", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "s", 3, ""},
{"retrigger_smooth", "No Retrigger Smooth", "Envelope", Kind::continuous, 0.0, 0.0, 10.0, 0.5, 1.0, "ms", 1, ""},
{"pitch_env", "Pitch Env", "Envelope", Kind::continuous, 0.0, -48.0, 48.0, 0.1, 1.0, "semitones", 1, ""},
{"pan_env", "Pan Env", "Envelope", Kind::continuous, 0.0, -100.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"vel_attack_depth", "Velocity Sample Start Depth", "Envelope", Kind::continuous, 0.0, 0.0, 100.0, 1.0, 10.0, "%", 0, ""},
{"lp_on", "LP", "Low pass filter", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"lp_cutoff", "LP Cutoff", "Low pass filter", Kind::continuous, 1.0, 0.0, 1.0, 0.001, 0.05, "", 3, ""},
{"lp_resonance", "LP Resonance", "Low pass filter", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lp_env_amount", "LP Env", "Low pass filter", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lp_env_attack", "LP Env Attack", "Low pass filter", Kind::continuous, 0.005, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"lp_env_decay", "LP Env Decay", "Low pass filter", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"lp_env_sustain", "LP Env Sustain", "Low pass filter", Kind::continuous, 1.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lp_env_release", "LP Env Release", "Low pass filter", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"lp_vel_amount", "LP Velocity", "Low pass filter", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lp_key_follow", "LP Key Follow", "Low pass filter", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"hp_on", "HP", "High pass filter", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"hp_cutoff", "HP Cutoff", "High pass filter", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.05, "", 3, ""},
{"hp_resonance", "HP Resonance", "High pass filter", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"hp_env_amount", "HP Env", "High pass filter", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"hp_env_attack", "HP Env Attack", "High pass filter", Kind::continuous, 0.005, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"hp_env_decay", "HP Env Decay", "High pass filter", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"hp_env_sustain", "HP Env Sustain", "High pass filter", Kind::continuous, 1.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"hp_env_release", "HP Env Release", "High pass filter", Kind::continuous, 0.1, 0.0, 20.0, 0.001, 0.01, "", 3, ""},
{"hp_vel_amount", "HP Velocity", "High pass filter", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo1_rate", "LFO 1 Frequency", "LFO 1", Kind::continuous, 4.0, 0.001, 512.0, 0.001, 0.1, "", 3, ""},
{"lfo1_mode", "LFO 1 Mode", "LFO 1", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Free|Trigger"},
{"lfo1_bpm_sync", "LFO 1 BPM Sync", "LFO 1", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"lfo1_one_shot", "LFO 1 One Shot", "LFO 1", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"lfo1_wave", "LFO 1 Waveform", "LFO 1", Kind::enumeration, 0.0, 0.0, 5.0, 1.0, 1.0, "", 0, "Sine|Triangle|Saw Up|Saw Down|Square|Sample And Hold"},
{"lfo1_delay", "LFO 1 Delay", "LFO 1", Kind::continuous, 0.0, 0.0, 10.0, 0.001, 0.01, "s", 3, ""},
{"lfo1_smoothing", "LFO 1 Smoothing", "LFO 1", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo1_volume_depth", "LFO 1 Volume Depth", "LFO 1", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo1_pan_depth", "LFO 1 Pan Depth", "LFO 1", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo1_lp_depth", "LFO 1 LP Depth", "LFO 1", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo1_hp_depth", "LFO 1 HP Depth", "LFO 1", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo1_pitch_depth", "LFO 1 Pitch Depth", "LFO 1", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo1_sample_depth", "LFO 1 Sample Move Depth", "LFO 1", Kind::continuous, 0.0, -100.0, 100.0, 0.001, 0.01, "%", 3, ""},
{"lfo2_rate", "LFO 2 Frequency", "LFO 2", Kind::continuous, 4.0, 0.001, 512.0, 0.001, 0.1, "", 3, ""},
{"lfo2_mode", "LFO 2 Mode", "LFO 2", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Free|Trigger"},
{"lfo2_bpm_sync", "LFO 2 BPM Sync", "LFO 2", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"lfo2_one_shot", "LFO 2 One Shot", "LFO 2", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"lfo2_wave", "LFO 2 Waveform", "LFO 2", Kind::enumeration, 0.0, 0.0, 5.0, 1.0, 1.0, "", 0, "Sine|Triangle|Saw Up|Saw Down|Square|Sample And Hold"},
{"lfo2_delay", "LFO 2 Delay", "LFO 2", Kind::continuous, 0.0, 0.0, 10.0, 0.001, 0.01, "s", 3, ""},
{"lfo2_smoothing", "LFO 2 Smoothing", "LFO 2", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo2_volume_depth", "LFO 2 Volume Depth", "LFO 2", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo2_pan_depth", "LFO 2 Pan Depth", "LFO 2", Kind::continuous, 0.0, -1.0, 1.0, 0.001, 0.01, "", 3, ""},
{"lfo2_lp_depth", "LFO 2 LP Depth", "LFO 2", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo2_hp_depth", "LFO 2 HP Depth", "LFO 2", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo2_pitch_depth", "LFO 2 Pitch Depth", "LFO 2", Kind::continuous, 0.0, -96.0, 96.0, 0.1, 1.0, "semitones", 1, ""},
{"lfo2_mod_pitch_depth", "Mod Wheel LFO 2 Pitch Depth", "LFO 2", Kind::continuous, 2.0, -24.0, 24.0, 0.01, 0.1, "semitones", 2, ""},
{"lfo2_sample_depth", "LFO 2 Sample Move Depth", "LFO 2", Kind::continuous, 0.0, -100.0, 100.0, 0.001, 0.01, "%", 3, ""},
{"global_release_loops", "Release Loop", "Loops", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"loop_crossfade", "Loop Crossfade", "Loops", Kind::continuous, 0, 0, 200, 0.01, 1, "ms", 2, ""},
{"drive_type", "Drive RAM", "Drive", Kind::enumeration, 0.0, 0.0, 3.0, 1.0, 1.0, "", 0, "Off|Tape|Soft Clip|Digital Clip"},
{"drive_amount", "Drive Amount", "Drive", Kind::continuous, 0.0, 0.0, 100.0, 0.1, 5.0, "%", 1, ""},
{"drive_position", "Drive Position", "Drive", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Before Comp Gate|After Comp Gate"},
{"comp_on", "Comp", "Dynamics", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"comp_threshold", "Comp Threshold", "Dynamics", Kind::continuous, -18.0, -60.0, 0.0, 0.1, 1.0, "dB", 1, ""},
{"comp_ratio", "Comp Ratio", "Dynamics", Kind::continuous, 4.0, 1.0, 20.0, 0.1, 1.0, "", 1, ""},
{"comp_attack", "Comp Attack", "Dynamics", Kind::continuous, 5.0, 0.1, 100.0, 0.1, 1.0, "ms", 1, ""},
{"comp_release", "Comp Release", "Dynamics", Kind::continuous, 80.0, 1.0, 10000.0, 1.0, 25.0, "ms", 0, ""},
{"comp_makeup", "Comp Makeup", "Dynamics", Kind::continuous, 0.0, 0.0, 24.0, 0.1, 1.0, "dB", 1, ""},
{"comp_mix", "Comp Mix", "Dynamics", Kind::continuous, 100.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"comp_delta", "Comp Delta Solo", "Dynamics", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"dynamics_order", "Comp Order", "Dynamics", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Comp Before Gate|Comp After Gate"},
{"gate_on", "Gate", "Gate", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"gate_threshold", "Gate Threshold", "Gate", Kind::continuous, -60.0, -90.0, 0.0, 0.1, 1.0, "dB", 1, ""},
{"gate_attack", "Gate Attack", "Gate", Kind::continuous, 1.0, 0.1, 100.0, 0.1, 1.0, "ms", 1, ""},
{"gate_release", "Gate Release", "Gate", Kind::continuous, 120.0, 1.0, 2000.0, 1.0, 25.0, "ms", 0, ""},
{"gate_hold", "Gate Hold", "Gate", Kind::continuous, 0.0, 0.0, 10000.0, 1.0, 25.0, "ms", 0, ""},
{"gate_depth", "Gate Depth", "Gate", Kind::continuous, 80.0, 0.0, 120.0, 0.1, 1.0, "dB", 1, ""},
{"gate_mix", "Gate Mix", "Gate", Kind::continuous, 100.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"gate_delta", "Gate Delta Solo", "Gate", Kind::enumeration, 0.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"},
{"ring_mode", "Ring", "Ring and degrade", Kind::enumeration, 0.0, 0.0, 2.0, 1.0, 1.0, "", 0, "Off|Fixed|Follow"},
{"ring_wave", "Ring Wave", "Ring and degrade", Kind::enumeration, 0.0, 0.0, 5.0, 1.0, 1.0, "", 0, "Sine|Triangle|Saw Up|Saw Down|Square|Noise"},
{"ring_amount", "Ring Amount", "Ring and degrade", Kind::continuous, 0.0, 0.0, 1.0, 0.001, 0.01, "", 3, ""},
{"ring_freq", "Ring Freq", "Ring and degrade", Kind::continuous, 440.0, 1.0, 20000.0, 1.0, 100.0, "Hz", 0, ""},
{"degrade_amount", "Degrade Amount", "Ring and degrade", Kind::continuous, 0.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"degrade_bits", "Degrade Bits", "Ring and degrade", Kind::integer, 8.0, 1.0, 16.0, 1.0, 1.0, "bits", 0, ""},
{"degrade_hold", "Degrade Hold", "Ring and degrade", Kind::integer, 4.0, 1.0, 64.0, 1.0, 4.0, "samples", 0, ""},
{"degrade_jitter", "Degrade Jitter", "Ring and degrade", Kind::continuous, 0.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"fm_amount", "FM Amount", "Ring and degrade", Kind::continuous, 0.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""},
{"fm_ratio", "FM Ratio", "Ring and degrade", Kind::continuous, 1.0, 0.125, 64.0, 0.125, 1.0, "", 3, ""},
{"fm_wave", "FM Wave", "Ring and degrade", Kind::enumeration, 0.0, 0.0, 5.0, 1.0, 1.0, "", 0, "Sine|Triangle|Saw Up|Saw Down|Square|Noise"},
{"fm_feedback", "FM Feedback", "Ring and degrade", Kind::continuous, 0.0, 0.0, 100.0, 0.1, 1.0, "%", 1, ""}
}};
enum class GlobalP { master_output_gain, output_stage, bus_glue, bus_soft_drive, output_ceiling, count };
inline constexpr int globalParameterCount = 5;
inline constexpr std::array<Descriptor, globalParameterCount> globalParameters {{
{"master_output_gain", "Master Output Gain", "Output", Kind::continuous, 0.0, -120.0, 24.0, 0.1, 1.0, "dB", 1, ""},
{"output_stage", "Output Stage", "Output", Kind::enumeration, 1.0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|LR-608"},
{"bus_glue", "Bus Glue", "Output", Kind::continuous, 35.0, 0.0, 100.0, 0.01, 1.0, "%", 2, ""},
{"bus_soft_drive", "Bus Soft Drive", "Output", Kind::continuous, 0.0, 0.0, 100.0, 0.01, 1.0, "%", 2, ""},
{"output_ceiling", "Output Ceiling", "Output", Kind::continuous, 0.98, 0.1, 1.0, 0.001, 0.01, "", 3, ""}
}};
inline constexpr std::array<Descriptor, loopParameterCount> loopParameters {{
{"loop_start", "Start", "Loops", Kind::continuous, 0, 0.0, 100.0, 0.0001, 0.01, "%", 6, ""},
{"loop_end", "End", "Loops", Kind::continuous, 100, 0.0, 100.0, 0.0001, 0.01, "%", 6, ""},
{"loop_repeats", "Repeats", "Loops", Kind::integer, 0, 0.0, 128.0, 1.0, 8.0, "", 0, ""},
{"loop_fade_in", "Fade In", "Loops", Kind::continuous, 0, 0.0, 200.0, 0.01, 1.0, "ms", 2, ""},
{"loop_fade_out", "Fade Out", "Loops", Kind::continuous, 0, 0.0, 200.0, 0.01, 1.0, "ms", 2, ""},
{"loop_pitch_down", "Repeat Pitch Amount", "Loops", Kind::continuous, 0, -48.0, 48.0, 0.01, 1.0, "semitones", 2, ""},
{"loop_lp_down", "Repeat LP Amount", "Loops", Kind::continuous, 0, -96.0, 96.0, 0.01, 1.0, "semitones", 2, ""},
{"loop_hp_down", "Repeat HP Amount", "Loops", Kind::continuous, 0, -96.0, 96.0, 0.01, 1.0, "semitones", 2, ""},
{"loop_one_shot", "One Shot", "Loops", Kind::enumeration, 0, 0.0, 1.0, 1.0, 1.0, "", 0, "Off|On"}
}};
enum class Action { none, sampleZero, loopZero };
struct GridEntry { int parameter = -1, loop = -1; Action action = Action::none; const char* category = ""; int global = -1; };
inline constexpr std::array<GridEntry, 161> grid {{
{int(P::input_gain), -1, Action::none, "Slot"},
{int(P::polyphony), -1, Action::none, "Slot"},
{int(P::slot_polyphony), -1, Action::none, "Slot"},
{int(P::poly_drift), -1, Action::none, "Slot"},
{int(P::portamento), -1, Action::none, "Slot"},
{int(P::legato), -1, Action::none, "Slot"},
{int(P::sustain_pedal), -1, Action::none, "Slot"},
{int(P::same_note_replace), -1, Action::none, "Slot"},
{int(P::pitch_bend_range), -1, Action::none, "Slot"},
{int(P::mode), -1, Action::none, "Slot"},
{int(P::output_route), -1, Action::none, "Slot"},
{int(P::ram_stereo_width), -1, Action::none, "Slot"},
{int(P::ram_swap_lr), -1, Action::none, "Slot"},
{int(P::ram_downsample), -1, Action::none, "Slot"},
{int(P::pan), -1, Action::none, "Slot"},
{int(P::low), -1, Action::none, "Mapping"},
{int(P::high), -1, Action::none, "Mapping"},
{int(P::root), -1, Action::none, "Mapping"},
{int(P::octave), -1, Action::none, "Mapping"},
{int(P::voice_pitch), -1, Action::none, "Mapping"},
{int(P::vel_volume_depth), -1, Action::none, "Mapping"},
{int(P::velocity_low), -1, Action::none, "Mapping"},
{int(P::velocity_high), -1, Action::none, "Mapping"},
{int(P::choke_trigger), -1, Action::none, "Mapping"},
{int(P::choke_target), -1, Action::none, "Mapping"},
{int(P::choke_mode), -1, Action::none, "Mapping"},
{int(P::sample_start), -1, Action::none, "Sample Window"},
{int(P::sample_end), -1, Action::none, "Sample Window"},
{int(P::start_threshold), -1, Action::none, "Sample Window"},
{int(P::end_threshold), -1, Action::none, "Sample Window"},
{int(P::end_preview_length), -1, Action::none, "Sample Window"},
{-1, -1, Action::sampleZero, "Sample Window"},
{int(P::global_one_shot), -1, Action::none, "Sample Window"},
{int(P::start_end_fade), -1, Action::none, "Sample Window"},
{int(P::stereo_delay_left), -1, Action::none, "Sample Window"},
{int(P::stereo_delay_right), -1, Action::none, "Sample Window"},
{int(P::stretch_amount), -1, Action::none, "Sample Window"},
{int(P::stretch_frequency), -1, Action::none, "Sample Window"},
{int(P::normalize_on), -1, Action::none, "Audio Sculpt"},
{int(P::normalize_target), -1, Action::none, "Audio Sculpt"},
{int(P::transient_shape), -1, Action::none, "Audio Sculpt"},
{int(P::transient_speed), -1, Action::none, "Audio Sculpt"},
{int(P::transient_mix), -1, Action::none, "Audio Sculpt"},
{int(P::ram_fade_in), -1, Action::none, "Audio Sculpt"},
{int(P::ram_fade_out), -1, Action::none, "Audio Sculpt"},
{int(P::ram_reverse), -1, Action::none, "Audio Sculpt"},
{int(P::dc_remove), -1, Action::none, "Audio Sculpt"},
{int(P::machine_character), -1, Action::none, "Machine"},
{int(P::character_depth), -1, Action::none, "Machine"},
{int(P::character_input_drive), -1, Action::none, "Machine"},
{int(P::character_converter), -1, Action::none, "Machine"},
{int(P::character_playback_life), -1, Action::none, "Machine"},
{int(P::character_repeat_life), -1, Action::none, "Machine"},
{int(P::character_air_body), -1, Action::none, "Machine"},
{int(P::character_output_glue), -1, Action::none, "Machine"},
{int(P::attack), -1, Action::none, "Envelope"},
{int(P::decay), -1, Action::none, "Envelope"},
{int(P::sustain), -1, Action::none, "Envelope"},
{int(P::release), -1, Action::none, "Envelope"},
{int(P::retrigger_smooth), -1, Action::none, "Envelope"},
{int(P::pitch_env), -1, Action::none, "Envelope"},
{int(P::pan_env), -1, Action::none, "Envelope"},
{int(P::vel_attack_depth), -1, Action::none, "Envelope"},
{int(P::lp_on), -1, Action::none, "Low pass filter"},
{int(P::lp_cutoff), -1, Action::none, "Low pass filter"},
{int(P::lp_resonance), -1, Action::none, "Low pass filter"},
{int(P::lp_env_amount), -1, Action::none, "Low pass filter"},
{int(P::lp_env_attack), -1, Action::none, "Low pass filter"},
{int(P::lp_env_decay), -1, Action::none, "Low pass filter"},
{int(P::lp_env_sustain), -1, Action::none, "Low pass filter"},
{int(P::lp_env_release), -1, Action::none, "Low pass filter"},
{int(P::lp_vel_amount), -1, Action::none, "Low pass filter"},
{int(P::lp_key_follow), -1, Action::none, "Low pass filter"},
{int(P::hp_on), -1, Action::none, "High pass filter"},
{int(P::hp_cutoff), -1, Action::none, "High pass filter"},
{int(P::hp_resonance), -1, Action::none, "High pass filter"},
{int(P::hp_env_amount), -1, Action::none, "High pass filter"},
{int(P::hp_env_attack), -1, Action::none, "High pass filter"},
{int(P::hp_env_decay), -1, Action::none, "High pass filter"},
{int(P::hp_env_sustain), -1, Action::none, "High pass filter"},
{int(P::hp_env_release), -1, Action::none, "High pass filter"},
{int(P::hp_vel_amount), -1, Action::none, "High pass filter"},
{int(P::lfo1_rate), -1, Action::none, "LFO 1"},
{int(P::lfo1_mode), -1, Action::none, "LFO 1"},
{int(P::lfo1_bpm_sync), -1, Action::none, "LFO 1"},
{int(P::lfo1_one_shot), -1, Action::none, "LFO 1"},
{int(P::lfo1_wave), -1, Action::none, "LFO 1"},
{int(P::lfo1_delay), -1, Action::none, "LFO 1"},
{int(P::lfo1_smoothing), -1, Action::none, "LFO 1"},
{int(P::lfo1_volume_depth), -1, Action::none, "LFO 1"},
{int(P::lfo1_pan_depth), -1, Action::none, "LFO 1"},
{int(P::lfo1_lp_depth), -1, Action::none, "LFO 1"},
{int(P::lfo1_hp_depth), -1, Action::none, "LFO 1"},
{int(P::lfo1_pitch_depth), -1, Action::none, "LFO 1"},
{int(P::lfo1_sample_depth), -1, Action::none, "LFO 1"},
{int(P::lfo2_rate), -1, Action::none, "LFO 2"},
{int(P::lfo2_mode), -1, Action::none, "LFO 2"},
{int(P::lfo2_bpm_sync), -1, Action::none, "LFO 2"},
{int(P::lfo2_one_shot), -1, Action::none, "LFO 2"},
{int(P::lfo2_wave), -1, Action::none, "LFO 2"},
{int(P::lfo2_delay), -1, Action::none, "LFO 2"},
{int(P::lfo2_smoothing), -1, Action::none, "LFO 2"},
{int(P::lfo2_volume_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_pan_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_lp_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_hp_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_pitch_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_mod_pitch_depth), -1, Action::none, "LFO 2"},
{int(P::lfo2_sample_depth), -1, Action::none, "LFO 2"},
{-1, 0, Action::none, "Loops"},
{-1, 1, Action::none, "Loops"},
{-1, -1, Action::loopZero, "Loops"},
{int(P::global_one_shot), -1, Action::none, "Loops"},
{-1, 2, Action::none, "Loops"},
{-1, 3, Action::none, "Loops"},
{-1, 4, Action::none, "Loops"},
{-1, 5, Action::none, "Loops"},
{-1, 6, Action::none, "Loops"},
{-1, 7, Action::none, "Loops"},
{-1, 8, Action::none, "Loops"},
{int(P::global_release_loops), -1, Action::none, "Loops"},
{int(P::release), -1, Action::none, "Loops"},
{int(P::loop_crossfade), -1, Action::none, "Loops"},
{int(P::drive_type), -1, Action::none, "Drive"},
{int(P::drive_amount), -1, Action::none, "Drive"},
{int(P::drive_position), -1, Action::none, "Drive"},
{int(P::comp_on), -1, Action::none, "Dynamics"},
{int(P::comp_threshold), -1, Action::none, "Dynamics"},
{int(P::comp_ratio), -1, Action::none, "Dynamics"},
{int(P::comp_attack), -1, Action::none, "Dynamics"},
{int(P::comp_release), -1, Action::none, "Dynamics"},
{int(P::comp_makeup), -1, Action::none, "Dynamics"},
{int(P::comp_mix), -1, Action::none, "Dynamics"},
{int(P::comp_delta), -1, Action::none, "Dynamics"},
{int(P::dynamics_order), -1, Action::none, "Dynamics"},
{int(P::gate_on), -1, Action::none, "Gate"},
{int(P::gate_threshold), -1, Action::none, "Gate"},
{int(P::gate_attack), -1, Action::none, "Gate"},
{int(P::gate_release), -1, Action::none, "Gate"},
{int(P::gate_hold), -1, Action::none, "Gate"},
{int(P::gate_depth), -1, Action::none, "Gate"},
{int(P::gate_mix), -1, Action::none, "Gate"},
{int(P::gate_delta), -1, Action::none, "Gate"},
{int(P::dynamics_order), -1, Action::none, "Gate"},
{int(P::ring_mode), -1, Action::none, "Ring and degrade"},
{int(P::ring_wave), -1, Action::none, "Ring and degrade"},
{int(P::ring_amount), -1, Action::none, "Ring and degrade"},
{int(P::ring_freq), -1, Action::none, "Ring and degrade"},
{int(P::degrade_amount), -1, Action::none, "Ring and degrade"},
{int(P::degrade_bits), -1, Action::none, "Ring and degrade"},
{int(P::degrade_hold), -1, Action::none, "Ring and degrade"},
{int(P::degrade_jitter), -1, Action::none, "Ring and degrade"},
{int(P::fm_amount), -1, Action::none, "Ring and degrade"},
{int(P::fm_ratio), -1, Action::none, "Ring and degrade"},
{int(P::fm_wave), -1, Action::none, "Ring and degrade"},
{int(P::fm_feedback), -1, Action::none, "Ring and degrade"},
{-1, -1, Action::none, "Output", int(GlobalP::master_output_gain)},
{-1, -1, Action::none, "Output", int(GlobalP::output_stage)},
{-1, -1, Action::none, "Output", int(GlobalP::bus_glue)},
{-1, -1, Action::none, "Output", int(GlobalP::bus_soft_drive)},
{-1, -1, Action::none, "Output", int(GlobalP::output_ceiling)},
}};
inline constexpr Descriptor zeroAction {"zero_crossing", "Zero Crossing", "", Kind::action, 0,0,1,1,1,"",0,"Off|Apply"};
inline const Descriptor& descriptor(const GridEntry& e) noexcept {
    return e.action != Action::none ? zeroAction
         : e.global >= 0 ? globalParameters[size_t(e.global)]
         : e.loop >= 0 ? loopParameters[size_t(e.loop)]
         : parameters[size_t(e.parameter)];
}
inline double sanitise(const Descriptor& d, double v) noexcept {
    if (!std::isfinite(v)) return d.initial;
    v = std::clamp(v, d.minimum, d.maximum);
    if (d.kind == Kind::integer || d.kind == Kind::enumeration || d.kind == Kind::note) v = std::round(v);
    return v;
}
struct SlotParameters {
    std::array<double, parameterCount> values {};
    std::array<std::array<double, loopParameterCount>, loopCount> loops {};
    SlotParameters() noexcept {
        for (size_t i=0;i<values.size();++i) values[i]=parameters[i].initial;
        for (auto& loop : loops) for (size_t i=0;i<loop.size();++i) loop[i]=loopParameters[i].initial;
    }
    double operator[](P p) const noexcept { return values[size_t(p)]; }
    double& operator[](P p) noexcept { return values[size_t(p)]; }
    double loop(int index, L field) const noexcept { return loops[size_t(index)][size_t(field)]; }
    double get(const GridEntry& e, int selectedLoop) const noexcept {
        return e.action != Action::none ? 0 : e.loop >= 0 ? loops[size_t(selectedLoop)][size_t(e.loop)] : values[size_t(e.parameter)];
    }
    void set(const GridEntry& e, int selectedLoop, double value) noexcept {
        if (e.action != Action::none) return;
        (e.loop >= 0 ? loops[size_t(selectedLoop)][size_t(e.loop)] : values[size_t(e.parameter)]) = sanitise(descriptor(e),value);
    }
};
} // namespace lsampler
